"""Gitconfig deploy — conf.d fragments, includes, gitignore, allowed signers.

Mirrors the logic of ``roles/gitconfig/tasks/`` (``main.yml`` and its included
task files ``collect_profile_fragments.yml``, ``cleanup_dead_symlinks.yml``,
``symlink_fragment.yml``, ``generate_includes.yml``, ``aggregate_gitignore.yml``,
``aggregate_allowed_signers.yml``).

Each profile may contribute, under ``files/gitconfig/``:
  - ``*.gitconfig`` fragments — symlinked into ``~/.config/git/conf.d`` under a
    priority-prefixed name and aggregated into a single ``includes.gitconfig``.
  - a ``gitignore`` file — concatenated (with profile headers) into the global
    ``~/.config/git/gitignore``.

Profiles may also declare ``git_allowed_signers`` in their config, which is
aggregated into ``~/.config/git/allowed_signers`` (resolving ``github_user``
entries to concrete SSH signing keys via the ``gh`` CLI at build time).

Build-time fact gathering:
  Fragment discovery, gitignore reads, and GitHub signing-key fetches all happen
  while the deploy code runs (before any operation executes). This is correct —
  it mirrors the Ansible role's ``find`` / ``slurp`` / filter-plugin resolution,
  none of which depend on a prior file-mutating operation.

This writes shared config files, so the orchestrator must call it with the
aggregated set of *all* enabled profiles (mirroring ``all_profiles=True`` in the
old aggregation lookup), not just a ``-p`` selected subset.
"""

from __future__ import annotations

import functools
import io
import shlex
import shutil
import subprocess
from pathlib import Path
from typing import Any

from pyinfra import logger
from pyinfra.operations import files, server

# Destination paths (mirror roles/gitconfig/defaults/main.yml). Resolved to
# absolute paths so includes/symlink targets do not depend on shell ``~``
# expansion.
CONF_D = Path.home() / ".config" / "git" / "conf.d"
INCLUDES_FILE = CONF_D / "includes.gitconfig"
GITIGNORE_FILE = Path.home() / ".config" / "git" / "gitignore"
ALLOWED_SIGNERS_FILE = Path.home() / ".config" / "git" / "allowed_signers"

_GENERATED_HEADER = "# Auto-generated by dotfiles — do not edit"


def deploy(profiles: list, dotfiles_dir: Path) -> None:
    """Deploy git conf.d fragments, includes, gitignore, and allowed signers.

    Args:
        profiles: ``ProfileInfo`` objects for every enabled profile, sorted by
            priority ascending.
        dotfiles_dir: Root of the dotfiles repository. Unused here (fragment
            sources come from each profile's ``path``); accepted for signature
            parity with the other config deploys.
    """
    del dotfiles_dir  # unused — kept for signature parity

    fragments = _collect_fragments(profiles)
    gitignore_sources = _collect_gitignore_sources(profiles)
    signer_entries = _collect_allowed_signers(profiles)

    # --- 3. Ensure conf.d directory exists ----------------------------------
    files.directory(
        name="Ensure git conf.d directory exists (~/.config/git/conf.d/)",
        path=str(CONF_D),
        present=True,
        mode="755",
    )

    # --- 4. Clean dead symlinks in conf.d -----------------------------------
    # Removes broken symlinks (depth 1, do not follow) before relinking.
    server.shell(
        name="Clean dead symlinks in git conf.d (~/.config/git/conf.d/)",
        commands=[
            f"find {shlex.quote(str(CONF_D))} -maxdepth 1 -type l -not -follow "
            f"-delete 2>/dev/null || true"
        ],
    )

    # --- 5. Symlink each fragment into conf.d -------------------------------
    for fragment in fragments:
        target = CONF_D / fragment["target_name"]
        files.link(
            name=f"Symlink git fragment {fragment['target_name']}",
            path=str(target),
            target=str(fragment["source"]),
            force=True,
        )

    # --- 6. Generate includes.gitconfig -------------------------------------
    _write_includes(fragments)

    # --- 7. Aggregate gitignore ---------------------------------------------
    _write_gitignore(gitignore_sources)

    # --- 8. Aggregate allowed signers ---------------------------------------
    _write_allowed_signers(signer_entries)


# ---------------------------------------------------------------------------
# Step 1 — collect *.gitconfig fragments
# ---------------------------------------------------------------------------


def _collect_fragments(profiles: list) -> list[dict[str, Any]]:
    """Collect ``*.gitconfig`` fragments from every profile's ``files/gitconfig``.

    Each fragment is recorded as ``{source, target_name, priority, profile}``.
    ``target_name`` is ``{priority:04d}-{profile}-{filename}`` (e.g.
    ``0100-shell-aliases.gitconfig``) so lexical sort == priority order.
    """
    fragments: list[dict[str, Any]] = []
    for profile in profiles:
        fragment_dir = profile.path / "files" / "gitconfig"
        if not fragment_dir.is_dir():
            continue
        # Non-recursive: only direct ``*.gitconfig`` children. Sorted by file
        # name to match the Ansible role's deterministic per-profile ordering.
        for source in sorted(fragment_dir.glob("*.gitconfig")):
            if not source.is_file():
                continue
            fragments.append(
                {
                    "source": source,
                    "target_name": f"{profile.priority:04d}-{profile.name}-{source.name}",
                    "priority": profile.priority,
                    "profile": profile.name,
                }
            )
    return fragments


# ---------------------------------------------------------------------------
# Step 1 (cont.) — collect gitignore sources
# ---------------------------------------------------------------------------


def _collect_gitignore_sources(profiles: list) -> list[dict[str, Any]]:
    """Collect each profile's ``files/gitconfig/gitignore`` file, if present."""
    sources: list[dict[str, Any]] = []
    for profile in profiles:
        gitignore = profile.path / "files" / "gitconfig" / "gitignore"
        if gitignore.is_file():
            sources.append(
                {
                    "path": gitignore,
                    "profile": profile.name,
                    "priority": profile.priority,
                }
            )
    return sources


# ---------------------------------------------------------------------------
# Step 2 — collect allowed signers
# ---------------------------------------------------------------------------


def _collect_allowed_signers(profiles: list) -> list[dict[str, Any]]:
    """Collect ``git_allowed_signers`` entries from every profile.

    Each entry is annotated with its ``profile`` and ``priority`` so the
    aggregated file can carry per-profile section headers.
    """
    entries: list[dict[str, Any]] = []
    for profile in profiles:
        for entry in profile.config.get("git_allowed_signers", []) or []:
            annotated = dict(entry)
            annotated["profile"] = profile.name
            annotated["priority"] = profile.priority
            entries.append(annotated)
    return entries


# ---------------------------------------------------------------------------
# Step 6 — includes.gitconfig
# ---------------------------------------------------------------------------


def _write_includes(fragments: list[dict[str, Any]]) -> None:
    """Write ``includes.gitconfig`` with one ``[include]`` per fragment.

    Fragments are sorted by ``target_name`` (lexical == priority order, since
    the priority prefix is zero-padded). Paths are absolute.
    """
    # Header, then an [include] block per fragment (tab-indented path, git style).
    out = [_GENERATED_HEADER]
    for fragment in sorted(fragments, key=lambda f: f["target_name"]):
        path = CONF_D / fragment["target_name"]
        out.append("[include]")
        out.append(f"\tpath = {path}")
    content = "\n".join(out) + "\n"

    files.put(
        name="Write git includes.gitconfig",
        src=io.BytesIO(content.encode()),
        dest=str(INCLUDES_FILE),
        mode="644",
    )


# ---------------------------------------------------------------------------
# Step 7 — aggregated gitignore
# ---------------------------------------------------------------------------


def _write_gitignore(sources: list[dict[str, Any]]) -> None:
    """Concatenate all profile gitignore files with per-profile headers.

    Sources are sorted by ``(priority, profile)``. Each section is prefixed with
    ``# --- {profile} (priority {N}) ---``.
    """
    if not sources:
        logger.debug("gitconfig: no gitignore sources — skipping gitignore write")
        return

    parts = [_GENERATED_HEADER]
    for source in sorted(sources, key=lambda s: (s["priority"], s["profile"])):
        body = source["path"].read_text()
        parts.append(f"# --- {source['profile']} (priority {source['priority']}) ---")
        parts.append(body.rstrip("\n"))
    content = "\n".join(parts) + "\n"

    files.directory(
        name="Ensure git config directory exists (~/.config/git/)",
        path=str(GITIGNORE_FILE.parent),
        present=True,
        mode="755",
    )
    files.put(
        name="Write aggregated git gitignore → ~/.config/git/gitignore",
        src=io.BytesIO(content.encode()),
        dest=str(GITIGNORE_FILE),
        mode="644",
    )


# ---------------------------------------------------------------------------
# Step 8 — aggregated allowed signers
# ---------------------------------------------------------------------------


def _write_allowed_signers(entries: list[dict[str, Any]]) -> None:
    """Aggregate allowed signers into a single file with per-profile headers.

    Entries are sorted by ``(priority, profile)`` so a profile's entries stay
    contiguous and headers don't fragment on equal priorities. ``github_user``
    entries are expanded (at build time) into one ``{email} {key}`` line per
    resolved signing key; direct ``key`` entries are emitted as-is.
    """
    if not entries:
        logger.debug("gitconfig: no allowed-signers entries — skipping write")
        return

    ordered = sorted(entries, key=lambda e: (e["priority"], e["profile"]))

    lines: list[str] = [_GENERATED_HEADER]
    current_profile: str | None = None
    for entry in ordered:
        email = entry.get("email")
        if not email:
            logger.warning(
                "gitconfig: allowed-signers entry without 'email' — skipping"
            )
            continue

        keys = _resolve_entry_keys(entry)
        if not keys:
            # Warning already emitted by the resolver for github_user misses.
            continue

        if entry["profile"] != current_profile:
            lines.append(f"# --- {entry['profile']} (priority {entry['priority']}) ---")
            current_profile = entry["profile"]

        for key in keys:
            lines.append(f"{email} {key}")

    # If every entry resolved to nothing, don't write a header-only file.
    if len(lines) == 1:
        logger.debug("gitconfig: allowed-signers resolved to no keys — skipping write")
        return

    content = "\n".join(lines) + "\n"

    files.directory(
        name="Ensure git config directory exists (~/.config/git/)",
        path=str(ALLOWED_SIGNERS_FILE.parent),
        present=True,
        mode="755",
    )
    files.put(
        name="Write aggregated git allowed_signers",
        src=io.BytesIO(content.encode()),
        dest=str(ALLOWED_SIGNERS_FILE),
        mode="644",
    )


def _resolve_entry_keys(entry: dict[str, Any]) -> list[str]:
    """Resolve a single allowed-signers entry to a list of SSH signing keys.

    - ``github_user`` present → fetch keys from GitHub via the ``gh`` CLI.
    - ``key`` present directly → use as-is.
    - neither → warn and return ``[]``.
    """
    if entry.get("github_user"):
        username = entry["github_user"]
        host = entry.get("github_host", "github.com")
        keys = list(_fetch_github_signing_keys(username, host))
        if not keys:
            logger.warning(
                f"gitconfig: no SSH signing keys for GitHub user "
                f"'{username}' on {host} — skipping entry"
            )
        return keys

    key = entry.get("key")
    if key:
        return [key]

    logger.warning(
        "gitconfig: allowed-signers entry has neither 'key' nor 'github_user' "
        "— skipping"
    )
    return []


@functools.lru_cache(maxsize=64)
def _fetch_github_signing_keys(username: str, host: str) -> tuple[str, ...]:
    """Fetch a GitHub user's SSH signing keys via the ``gh`` CLI (build time).

    Uses the list form of subprocess (no shell, no injection surface) and keys
    the cache on ``(username, host)`` so GitHub Enterprise hosts resolve
    independently. Returns a tuple (hashable for ``lru_cache``); empty on any
    failure, with a warning logged.
    """
    if not shutil.which("gh"):
        logger.warning(
            "gitconfig: 'gh' CLI not found — cannot resolve GitHub signing keys "
            f"for '{username}' on {host}"
        )
        return ()

    try:
        result = subprocess.run(
            [
                "gh",
                "api",
                "--hostname",
                host,
                f"/users/{username}/ssh_signing_keys",
                "--jq",
                ".[].key",
            ],
            capture_output=True,
            text=True,
            timeout=15,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        logger.warning(
            f"gitconfig: failed to fetch GitHub signing keys for '{username}' "
            f"on {host}: {exc}"
        )
        return ()

    if result.returncode != 0:
        logger.warning(
            f"gitconfig: gh api failed for '{username}' on {host}: "
            f"{result.stderr.strip()}"
        )
        return ()

    keys = tuple(line.strip() for line in result.stdout.splitlines() if line.strip())
    return keys
