"""SSH client config deploy — generate ``~/.ssh/config`` from merged profiles.

Mirrors the intent of ``roles/ssh_config/tasks/main.yml``. Unlike the Ansible
role (which merged host entries into an existing file via
``community.general.ssh_config`` and managed top/bottom blocks with
``blockinfile``), pyinfra has no equivalent ssh-config module. The simplest
correct approach — and the one the spec calls for — is to **generate the entire
file** from the merged data and write it whole.

Behavior note (intentional divergence from the Ansible role): this deploy *fully
owns* ``~/.ssh/config``. Any manually added or third-party entries are discarded
on every run. Persistent customizations should live in a profile's
``ssh_client_config`` / ``ssh_client_config_block`` instead.

File layout:
  1. Top blocks  — ``ssh_client_config_block`` entries with ``position: top``
  2. Host stanzas — one ``Host`` per present ``ssh_client_config`` entry
  3. Bottom blocks — ``ssh_client_config_block`` entries with ``position: bottom``

The whole file is generated at build time (it consumes only ``merged`` data) and
written with mode ``600`` into ``~/.ssh`` (created ``700`` first), as SSH
requires for client config.
"""

from __future__ import annotations

import io
from pathlib import Path
from typing import Any

from pyinfra import logger
from pyinfra.operations import files

_GENERATED_HEADER = "# Auto-generated by dotfiles — do not edit"

# Mapping from Ansible/profile field name → (SSH config key, is_boolean).
# Boolean fields are rendered as ``yes`` / ``no``. ``other_options`` is handled
# separately. Order here defines emission order within a Host stanza.
_FIELD_MAP: tuple[tuple[str, str, bool], ...] = (
    ("hostname", "HostName", False),
    ("port", "Port", False),
    ("remote_user", "User", False),
    ("identity_file", "IdentityFile", False),
    ("identities_only", "IdentitiesOnly", True),
    ("proxycommand", "ProxyCommand", False),
    ("proxyjump", "ProxyJump", False),
    ("forward_agent", "ForwardAgent", True),
    ("dynamicforward", "DynamicForward", False),
    ("strict_host_key_checking", "StrictHostKeyChecking", True),
    ("user_known_hosts_file", "UserKnownHostsFile", False),
    ("add_keys_to_agent", "AddKeysToAgent", True),
)


def deploy(merged: dict[str, Any]) -> None:
    """Generate and write ``~/.ssh/config`` from the merged profile data."""
    hosts: list[dict[str, Any]] = merged.get("ssh_client_config", []) or []
    blocks: list[dict[str, Any]] = merged.get("ssh_client_config_block", []) or []
    config_path = Path(merged.get("ssh_config_file", "~/.ssh/config")).expanduser()

    content = _render(hosts, blocks)

    # Ensure ~/.ssh exists with the strict mode SSH expects (0700) before
    # writing the 0600 config.
    files.directory(
        name="Ensure SSH config directory exists",
        path=str(config_path.parent),
        present=True,
        mode="700",
    )
    files.put(
        name="Write SSH client config",
        src=io.BytesIO(content.encode()),
        dest=str(config_path),
        mode="600",
    )


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _render(hosts: list[dict[str, Any]], blocks: list[dict[str, Any]]) -> str:
    """Assemble the full ssh config text from host entries and raw blocks."""
    sections: list[str] = [_GENERATED_HEADER]

    top = _block_content(blocks, "top")
    if top:
        sections.append(top)

    for entry in hosts:
        if entry.get("state", "present") == "absent":
            continue
        stanza = _render_host(entry)
        if stanza:
            sections.append(stanza)

    bottom = _block_content(blocks, "bottom")
    if bottom:
        sections.append(bottom)

    return "\n\n".join(sections) + "\n"


def _block_content(blocks: list[dict[str, Any]], position: str) -> str:
    """Concatenate raw block ``content`` for the given ``position`` (top/bottom)."""
    contents = [
        block["content"].rstrip("\n")
        for block in blocks
        if block.get("position") == position and block.get("content")
    ]
    return "\n".join(contents)


def _render_host(entry: dict[str, Any]) -> str:
    """Render a single ``Host`` stanza, emitting only fields that are present."""
    host = entry.get("host")
    if not host:
        logger.warning("ssh_config: entry without 'host' — skipping")
        return ""

    lines = [f"Host {host}"]

    for field, ssh_key, is_bool in _FIELD_MAP:
        if field not in entry or entry[field] is None:
            continue
        value = _yes_no(entry[field]) if is_bool else entry[field]
        lines.append(f"    {ssh_key} {value}")

    # Arbitrary extra options: dict of {SSHKey: Value}.
    for key, value in (entry.get("other_options") or {}).items():
        if value is None:
            continue
        lines.append(f"    {key} {value}")

    return "\n".join(lines)


def _yes_no(value: Any) -> str:
    """Render a boolean-ish value as SSH's ``yes`` / ``no``.

    Non-bool values (already a string like ``"yes"``) pass through unchanged so
    profiles can supply the literal SSH token if they prefer.
    """
    if isinstance(value, bool):
        return "yes" if value else "no"
    return str(value)
