---
# Hive CLI Configuration
# Documentation: https://github.com/anthropics/hive-cli
#
# Uncomment and modify options as needed.
# Values shown are defaults.
#
# Configuration precedence (highest to lowest):
#   1. Environment variables (HIVE_*)
#   2. .hive.local.yml (local overrides, git-ignored)
#   3. .hive.yml (project config, version-controlled)
#   4. $XDG_CONFIG_HOME/hive/hive.yml (global user config)
#   5. Package defaults

# agents:
#  order:
#    - claude
#     - gemini
#     - codex
#    - agent
#     - copilot

#   configs:
#     # Claude uses --continue flag
#     claude:
#       resume_args: ["--continue"]

#     # Copilot uses --continue flag
#     copilot:
#       resume_args: ["--continue"]

#     # Codex uses resume subcommand with --last
#     codex:
#       resume_args: ["resume", "--last"]

#     # Gemini uses --resume with latest argument
#     gemini:
#       resume_args: ["--resume", "latest"]

#     # Cursor agent CLI uses resume subcommand
#     agent:
#       resume_args: ["resume"]

#     # Cursor agent alternative name
#     cursor-agent:
#       resume_args: ["resume"]

resume:
  enabled: false

worktrees:
  enabled: true
  # parent_dir: ".worktrees"
  # use_home: false
  resume: true
#   copy_files: []
#   symlink_files: []

#   post_create:
#     - command: "mise trust"
#       if_exists: "mise.toml"

#     - command: "mise install"
#       if_exists: "mise.toml"

#     - command: "pnpm install --frozen-lockfile"
#       if_exists: "pnpm-lock.yaml"

#     - command: "yarn install --frozen-lockfile"
#       if_exists: "yarn.lock"

#     - command: "npm install"
#       if_exists: "package-lock.json"

#     - command: "uv sync"
#       if_exists: "pyproject.toml"

# zellij:
#   # layout: "agent"  # Optional: set to use a custom layout, omit for default
#   session_name: "{repo}-{agent}"

# github:
#   fetch_issues: true
#   issue_limit: 20
