" be iMproved
set nocompatible
filetype off

"""
" General
"""

set encoding=UTF-8
syntax enable                     " Enable syntax highlighting
set clipboard=unnamed             " Use OS X clipboard
set autoread                      " Auro reload on local changes
set nowritebackup                 " Disable backups
set noswapfile                    " Disable swap files
set history=999                   " Set history

set backspace=indent,eol,start    " Usual backspace behaviour

set shortmess+=I                  " Disable splash screen
set ruler                         " Show cursor position (if powerline is not loaded)
set cursorline                    " Highlight current line
set noerrorbells                  " Disable possible error messages
set ttyfast                       " Fast terminal connection
set hlsearch                      " Highlight search results
set ignorecase                    " Ignore cases ...
set smartcase                     " ... unless there is a capital letter
set incsearch                     " Display incremental searches
set number                        " Show absolut line numbers
"set relativenumber                " Show Relative line numbers
set numberwidth=4                 " Four columns for line numbers
set tabstop=2                     " Soft tabs, 2 characters
set softtabstop=2                 " "
set shiftwidth=2                  " "
set expandtab                     " "

"""
" vim-plug
"""

source ~/.vim/plug.vim

"""
" Plugin settings
"""

" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

"""
" NERDTree
"""

" Open NERDTree with <Ctrl+t>
map <C-t> :NERDTreeToggle<CR>
map <M-t> :NERDTreeToggle<CR>

" Start NERDTree, unless a file or session is specified, eg. vim -S session_file.vim.
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists('s:std_in') && v:this_session == '' | NERDTree | endif

" Github Copilot
let g:copilot_filetypes = {
  \ 'yaml': v:true,
  \ 'xml': v:true,
  \ 'gitcommit': v:true,
  \ }

"""
" EditorConfig
"""
" To ensure that editorconfig plugin works well with fugitive plugin:
let g:EditorConfig_exclude_patterns = ['fugitive://.*']

let g:EditorConfig_enable_for_new_buf = 1

let g:EditorConfig_indent_style = "space"
let g:EditorConfig_indent_size = 4
let g:EditorConfig_max_line_indicator = "line"

imap <M-]> <Plug>(copilot-next)
imap <M-[> <Plug>(copilot-previous)


"""
" Custom Syntax Highlighting associations
"""
au BufRead,BufNewFile Dockerfile* setfiletype dockerfile
au BufRead,BufNewFile .env.* setfiletype sh
au BufRead,BufNewFile .env-* setfiletype sh
au BufRead,BufNewFile *.json.* setfiletype json
au BufRead,BufNewFile *.json-* setfiletype json
au BufRead,BufNewFile *.yaml.* setfiletype yaml
au BufRead,BufNewFile *.yaml-* setfiletype yaml
