---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    role-file: requirements.yml

driver:
  name: docker

platforms:
  - name: dotfiles-test-ubuntu
    image: ubuntu:24.04
    pre_build_image: true
    command: /bin/bash -c "while true; do sleep 1000; done"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    environment:
      HOME: /root

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      gathering: implicit
  inventory:
    host_vars:
      dotfiles-test-ubuntu:
        ansible_python_interpreter: auto
        dotfiles_symlink_command: symlink-dotfiles
  playbooks:
    converge: converge.yml
    prepare: prepare.yml
    verify: verify.yml
  env:
    ANSIBLE_ROLES_PATH: "../../roles:~/.ansible/roles"
    ANSIBLE_COLLECTIONS_PATH: "../../.ansible/collections"
    ANSIBLE_LOOKUP_PLUGINS: "../../ansible_plugins/lookup"

verifier:
  name: testinfra
  options:
    v: true
    tb: short

scenario:
  name: default
  # Note: idempotence is tested in individual role tests (ssh_config, dotfiles).
  # Skipped here due to blockinfile edge case with insertbefore: BOF that only
  # manifests when running multiple roles together.
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
