---
- name: Destroy Tart macOS VM
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    molecule_instance_config: "{{ lookup('env', 'MOLECULE_INSTANCE_CONFIG') }}"
  tasks:
    - name: Check if Tart is installed
      ansible.builtin.command:
        cmd: which tart
      register: tart_check
      changed_when: false
      failed_when: false

    - name: Stop VM
      ansible.builtin.command:
        cmd: "tart stop {{ item.name }}"
      loop: "{{ molecule_yml.platforms }}"
      failed_when: false
      changed_when: true
      when: tart_check.rc == 0

    - name: Delete VM
      ansible.builtin.command:
        cmd: "tart delete {{ item.name }}"
      loop: "{{ molecule_yml.platforms }}"
      failed_when: false
      changed_when: true
      when: tart_check.rc == 0

    - name: Remove instance config
      ansible.builtin.file:
        path: "{{ molecule_instance_config }}"
        state: absent
